[firebase]
apiKey = "AIzaSyB9RRAz0k3tNAcOH2Eb6nwF5P4VGb5Q8EM"
authDomain = "mediscan-ai-bd957.firebaseapp.com"
databaseURL = "https://mediscan-ai-bd957-default-rtdb.firebaseio.com/"
projectId = "mediscan-ai-bd957"
storageBucket = "mediscan-ai-bd957.appspot.com"
messagingSenderId = "849624048358"
appId = "1:849624048358:web:0e8496e6438fc8e4211127"
measurementId = "G-YZ5TVD3CY7"
